### ISSUE TITLE
Add an autostart option

### ISSUE THREAD

**Issue by akien-mga** [dglent/meteo-qt#14] opened 2014-11-01 14:31 UTC
It would be nice to have meteo-qt start automatically with the desktop.

I'm not familiar about it but on the packaging side this could probably be done by adding a file to /etc/xdg/autostart. That's not the best solution IMO though, because it would be hard to disable.

With user privileges, it seems this could be achieved by adding a desktop file in ~/.config/autostart.
A tickable box in the meteo-qt settings could make it possible to add this desktop file or remove it easily ("Enable autostart"), and this has the advantage of being desktop-agnostic (at least I suppose).

**Comment by dglent** [comment] 2015-05-18 16:30
I tested in KDE4 , no problem detected so far. I close the issue.

**Closed by dglent** 2015-05-18 16:30 UTC

**Comment by pmattern** [comment] 2015-11-20 18:29
If meteo-qt gets launched by `$XDG_CONFIG_HOME/autostart/meteo-qt.desktop` on KDE Plasma 5 indeed one additional instance gets added to panel plugin (widget) "System Tray" each time a session is started, probably as the items within that plugin are somehow remembered independent from the way they were launched. Both [LXQt ConnMan applet](https://github.com/surlykke/lxqt-connman-applet) which is working well in KDE besides geared towards LXQt and [Octopi's](https://github.com/aarnt/octopi) notifier are launched similarly by desktop entry files in `$XDG_CONFIG_DIRS/autostart`, but only LXQt ConnMan applet behaves the same as meteo-qt while there's never more than a single instance of Octopi notifier.
Don't know the technical details. But in LXQt the context menus of all three panel objects in question (meteo-qt, LXQt ConnMan applet and Octopi notifier) have a single entry to terminate only while in KDE Plasma Octopi notifier has a single one only as well, the others have two. Maybe this corresponds to a different way Octopi declares how to get stopped which could in turn correspond to getting launched as single instance only?

**Comment by dglent** [comment] 2015-11-21 04:01
I tested Mageia Cauldron in Virtualbox with Plasma 5 (plasma-desktop-5.4.90-5.mga6) and i cannot reproduce it. I have always one instance of meteo-qt, with the startup at login enabled.
Something chagned ?

**Comment by pmattern** [comment] 2015-11-23 01:39
Strange.
In the meantime I could verify the behaviour both on Fedora 23 (KDE Plasma 5.4.3 as well) and openSUSE Leap 42.1 (5.4.2). Always the same finding as in this screenshot from Arch Linux
![kde-plasma-5_system-tray_multiple-instances](https://cloud.githubusercontent.com/assets/9860801/11327063/1d624330-917b-11e5-8960-c70f3e85d836.png)

Are some of the icons in System Tray by any chance hidden on your system? FWIW this can be avoided by checking System Tray Options (context menu) - System Tray Settings - Entries (left pane) - "Always show...".
Also, I wonder about that version 5.4.*90*. Don't know KDE's steadily changing naming and versioning too well. But isn't this a developer version and it could hence make sense to wait until it's gotten the next stable one?

Probably it's a KDE issue anyway as other applications behave the same. E. g. it could be a remnant of https://bugs.kde.org/show_bug.cgi?id=335878.
