### ISSUE TITLE
No Setting option in right click menu in KDE Plasma 5

### ISSUE THREAD

**Issue by anexation** [dglent/meteo-qt#34] opened 2015-01-02 06:19 UTC
There is No Setting option in right click menu in KDE Plasma 5, how can i configure settings?

![image](https://cloud.githubusercontent.com/assets/6136025/5594504/10bef8c8-9215-11e4-94f2-06041ecbf05d.png)

**Comment by dglent** [comment] 2015-01-02 06:48
Hello, i don't know why you have only a 'Quit' option, and with a different icon than this: https://github.com/dglent/meteo-qt/blob/master/meteo_qt/images/application-exit.png.

I will install kde plasma 5 to investigate it, thanks for reporting.

**Comment by anexation** [comment] 2015-01-02 06:51
i am the maintainer and lead developer of manjaro plasma 5 and wanted to included this in the iso.. an easy option to test develop is my iso if your interested..

https://forum.manjaro.org/index.php?topic=18150.0
https://sourceforge.net/projects/manjarotest/files/0.9.0/kf5-plasma-dev/

thanks for the quick replay.

AneX

**Comment by dglent** [comment] 2015-01-02 14:34
Thank you, i installed it in the virtualbox.
I could reproduce the issue.
The problem is that the left click is recognized correctly and the middle click is recognized as right click

Here there is the list with the activation reasons:
http://doc.qt.io/qt-5/qsystemtrayicon.html#ActivationReason-enum
but in Plasma 5 (manjaro live) that i tested:
the left click gives 3
the middle click gives 1
the right click gives nothing
the program doesn't listen at all the right click

Instead i have a pop up with only the "Quit" menu, as you show in the screenshot, which doesn't belongs to the application.

I don't know what is the cause, in Plasma 5 or in pyqt5.
Asuming that it works fine in lxqt, i suppose that something happen in Plasma 5 tray

Maybe i could apply a workaround for Plasma 5 but i don't know what exactly. The problem is with a mouse without a middle button

I will try to learn some more info about

**Comment by dglent** [comment] 2015-01-03 08:59
Please can you test the last commit ?
I tested in the virtualbox in manjaro using your images, with qt 5.4.0 and it is ok.
It adds the context menu in the systemtray context menu of Plasma5

If it is ok for you i will release a new version

**Comment by anexation** [comment] 2015-01-03 09:00
k

**Comment by anexation** [comment] 2015-01-03 10:03
Thank you very much, perfect..  https://aur.archlinux.org/packages/meteo-qt-git/

I will close this issue as soolved..

**Comment by dglent** [comment] 2015-01-03 10:15
Ok thanks, i will release the 0.4.4 during the day

**Comment by anexation** [comment] 2015-01-03 10:23
thank you very much, i don't know what distro or desktop you use but much appriciated.. https://forum.manjaro.org/index.php?topic=18150.msg175105#msg175105

**Comment by dglent** [comment] 2015-01-03 13:13
In the context menu there is a submenu 'Cities' where appear the extra configured cities, or a label "Empty list"
In plasma5 it doesn't work, i don't have the submenu.

**Comment by anexation** [comment] 2015-01-03 17:58
yes i can confirm that also

**Comment by dglent** [comment] 2015-01-10 13:58
We have good news for this:
https://codereview.qt-project.org/#/c/103280/2//ALL

If you have the possibility to test it please let me know.

**Comment by anexation** [comment] 2015-01-10 14:02
humm

**Comment by dglent** [comment] 2015-01-11 13:14
Finaly there is a new change for plasma5 system tray in qt which fixes the bug:
https://codereview.qt-project.org/103280
I couldn't install my 64bit packages in virtualbox as i discovered that i cannot have 64bit guest ...
I will have to build 32 bit package in the virtualbox with the above patch
I hope to have the time to do it this week.
If you have the possibility to test it please let me know

**Comment by anexation** [comment] 2015-01-11 14:08
Im compiling as we speak. I just git pulled qtbase and then git pulled the patch and .tar.gz up and then ran makepkg from konsole

```
# Maintainer: Jerome Leclanche <jerome@leclan.ch>
# Contributor: Andrea Scarpino <andrea@archlinux.org>
# Contributor: Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>

_pkgname=qt5-base
pkgname=$_pkgname
pkgver=5.4.0
pkgrel=2
pkgdesc="A cross-platform application and UI framework"
arch=("i686" "x86_64")
url="https://qt-project.org/"
license=("GPL3" "LGPL")
depends=(
	"dbus" "xcb-util-keysyms" "xcb-util-wm" "xcb-util-image"
	"libxext" "inputproto" "libgl" "libxkbcommon" "systemd"
	"libpng" "sqlite" "fontconfig" "icu" "libxrender"
)
makedepends=("postgresql-libs")
optdepends=(
	"qtchooser: set the default Qt toolkit"
	"postgresql-libs: PostgreSQL driver"
	"libmariadbclient: MariaDB driver"
	"unixodbc: ODBC driver"
	"libfbclient: Firebird/iBase driver"
)
provides=("$_pkgname")
conflicts=("$_pkgname-git")
source=("qtbase.tar.gz")
sha256sums=("77182644f11080e11c18d9baa3d68f9411d237cfca87fb909de5340bf7d3801a")

prepare() {
	cd "$srcdir/qtbase"
	sed -i "s|-O2|${CXXFLAGS}|" mkspecs/common/{g++,gcc}-base.conf
	sed -i "/^QMAKE_LFLAGS_RPATH/s| -Wl,-rpath,||g" "mkspecs/common/gcc-base-unix.conf"
	sed -i "/^QMAKE_LFLAGS\s/s|+=|+= ${LDFLAGS}|g" "mkspecs/common/gcc-base.conf"
}

build() {
	cd "$srcdir/qtbase"

	./configure -confirm-license -opensource \
		-prefix /usr \
		-bindir /usr/lib/qt/bin \
		-docdir /usr/share/doc/qt \
		-headerdir /usr/include/qt \
		-archdatadir /usr/lib/qt \
		-datadir /usr/share/qt \
		-sysconfdir /etc/xdg \
		-examplesdir /usr/share/doc/qt/examples \
		-system-sqlite \
		-openssl-linked \
		-nomake examples \
		-nomake tests \
		-no-rpath \
		-optimized-qmake \
		-dbus-linked \
		-reduce-relocations \
		-opengl es2
	make
}

package() {
	cd "$srcdir/qtbase"
	make INSTALL_ROOT="$pkgdir" install
}
```

**Comment by dglent** [comment] 2015-01-21 05:54
Finally this is the fix:
https://reviewboard.kde.org/r/122171/
i couldn't test it yet

**Comment by anexation** [comment] 2015-01-21 06:21
been really busy getting all my apps on the plasma5 iso to have non -git flags for repo and can be superseded when arch starts maintaining those packages, and making the new public release v1 iso.

http://sourceforge.net/projects/manjarotest/files/0.9.0/kf5-plasma-dev/

**Comment by dglent** [comment] 2015-05-18 17:54
For info: We still wait the patches to be applied in packages...
In these qt5 sources the systemtray patch is not applied yet:
http://download.qt.io/official_releases/qt/5.4/5.4.1/
Qt system tray patch:
https://codereview.qt-project.org/#/c/103280/

I didn't check yet in which version of KDE this patch (if) is applied:
https://git.reviewboard.kde.org/r/122171/diff/#index_header

**Comment by mitya57** [comment] 2015-05-18 18:11
@dglent The Qt fix will be in 5.4.2 (expected to be released this week). The KDE fix is in KDE Frameworks 5.7 (released three months ago).

**Comment by dglent** [comment] 2015-05-18 18:53
Thanks for the info

**Comment by dglent** [comment] 2015-10-24 07:40
Screenshot with the fix:
![](https://lut.im/mnoZY4qlXx/gOIy37ZMv6IKJdfn)

@mitya57 :+1:

**Closed by dglent** 2015-10-24 07:40 UTC
