### ISSUE TITLE
core dump for unknown reason

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#44] opened 2015-12-03 21:27 UTC
Running 5bd50c0 on up to date Arch Linux x86_64 there was a core dump for apparently no reason.
I'm not aware of anything particular that happened before.
So find a gdb backtrace on https://gist.github.com/pmattern/917ba17ac8635d4606ca for now and let me know if additional information is needed.

**Comment by dglent** [comment] 2015-12-19 07:52
Hi, is it reproducible ?

**Comment by pmattern** [comment] 2015-12-19 22:16
This still happens sporadically, e. g. last seen with 81c2230 some days ago, but I still didn't find a way to reproduce. Rather, I only get aware of meteo-qt missing in the panel a while after the crash took place (it's an application I look at from time to time only).
Backtrace from gdb always the same so far. Replaced the gist above with another one providing the stack trace seen when the core dump gets handed to `gdb` by `coredumpctl`, too.

**Comment by dglent** [comment] 2015-12-19 22:35
I had a similar problem and i had some messages in logs about crashes of the panel but was linked with a hdd problem...
Example:
Mar 28 06:01:25 localhost kernel: [   88.262017] meteo-qt[5725]: segfault at 0 ip 00007f9fc52b0533 sp 00007fff858ac768 error 4 in libQt5Core.so.5.4.0[7f9fc51aa000+4af000]
Mar 28 06:01:25 localhost kernel: [   88.262303] lxqt-session[5423]: segfault at 0 ip 00007f3182e9b533 sp 00007ffce6485b78 error 4 in libQt5Core.so.5.4.0[7f3182d95000+4af000]

If there are no other similar messages in system logs, maybe we can see at which point has stopped from the log file .config/meteo-qt/meteo-qt.log

Which version of qt5 you have ?

**Comment by pmattern** [comment] 2015-12-20 00:27
`~/.config/meteo-qt/meteo-qt.log` does not state any messages from the time meteo-qt crashed. But it shows that the crash took place exactly when another weather update was scheduled.
That aside `meteo-qt.log` shows an error message
`   ERROR: Error: <class 'RuntimeError'> - meteo_qt - root`
at the beginning of every weather update and another one
`   ERROR: Cannot find UV index - overview - root`
sporadically a couple of seconds after weather update has taken place.

Qt version is 5.5.1 as provided by Arch Linux.

**Comment by dglent** [comment] 2015-12-20 00:47
The runtime error happens when the dialogue is closed
https://github.com/dglent/meteo-qt/blob/master/meteo_qt/meteo_qt.py#L294
It is in the namespace but not any more as a dialogue (?) and it has n't the method isvisible() anymore 
If you leave the dialogue open you will not have this. You can leave it open to see if it will crash and maybe start it from the terminal.
I don't have any dysfunction here, and this error seems to be always, with the dialogue closed.
I have qt 5.4.0

**Comment by dglent** [comment] 2015-12-20 00:55
Also, if need it you can change the debug level in .config/meteo-qt/meteo-qt.conf to DEBUG in order to print more messages.

**Comment by pmattern** [comment] 2015-12-20 01:42
Those two error messages were mentioned for the sake of completeness only, so far there isn't any evidence that they are related to the problem discussed in this issue.

Not sure what you mean by "dialogue" but I can't seem to reproduce your findings. The runtime error message comes up if notifications according to the Desktop Notifications Specification are left alone and disappear after they time out only as well as if they aren't enabled at all ("Notification on weather update" in dialog "Meteo-qt Configuration" unchecked). The runtime error message also comes up if dialog "Meteo-qt Configuration" itself is opened.

> you can change the debug level in .config/meteo-qt/meteo-qt.conf to DEBUG

Will do.

**Comment by dglent** [comment] 2015-12-20 06:39
Peter, dialogue i mean the weather information window. When it is open, and you change the city, there is no runtime error message.

**Comment by dglent** [comment] 2016-01-22 07:22
Did you try after the above commit ?

**Comment by pmattern** [comment] 2016-01-24 02:09
First of all I got aware of your message of December 20th only when I re-visited this issue again by hazard some days ago. No clue why. But I'm running a script updating all VCS packages I'm using once every couple of days so meteo-qt was always up to date nevertheless.
According to systemd journal core dumps kept happening sporadically all the time but I didn't track an eventual trigger each time.

As of afeeaf1 core dumps can be reproduced 100% by re-opening dialog "Weather status", though: open the dialog by (left) clicking meteo-qt's panel icon, close dialog, try to reopen again right thereafter → core dump.
Stack trace and backtrace as described before look pretty similar but a bit more verbose (due to setting Level=DEBUG in `.config/meteo-qt/meteo-qt.conf`?) and were added to GIST https://gist.github.com/pmattern/917ba17ac8635d4606ca (`{stack,back}trace_afeeaf1.txt`).

On a side note those error messages `ERROR: Error: <class 'RuntimeError'> - meteo_qt - root` upon receiving weather updates cannot be seen any longer.

**Comment by dglent** [comment] 2016-01-24 07:20
I could reproduce this, it is a regression.
Fixed in the above commit, maybe it improves the initial crash as it improves the synchronization between pyqt and C++ objects (it deletes the instance ion pyqt when is closed in c++)
Lets see ...

**Comment by pmattern** [comment] 2016-08-24 10:52
The problem seems to persist.

Two days ago I saw another crash of this kind. It took place right when meteo-qt was about to fetch the current data. The traces were slightly different as before, see https://gist.github.com/pmattern/115f4f61c4391658762863288787ef82 which includes some additional message from systemd journal which may help tracking this down.

8c25c62 on Arch Linux.

**Comment by dglent** [comment] 2016-08-25 03:43
I saw this for the first time before a few days.
The above commit fix the crash.
However, i could reproduce it but the application has never stopped to run. 
After the crash i had wrong data but it was still running.
So it is not sur that solves the initial problem, let see ...

**Comment by pmattern** [comment] 2016-08-25 09:55
So 8ffd4fa is meant to address that message `IndexError: list index out of range` as stated in the Gist [linked above](https://github.com/dglent/meteo-qt/issues/44#issuecomment-242025292)?

**Comment by dglent** [comment] 2016-08-25 15:32
Την Πέμπτη, 25 Αυγούστου 2016 11:55:04 Π.Μ. CEST, Peter Mattern γράψατε:
> So 8ffd4fa is meant to address that message IndexError: list 
> index out of range as stated in the Gist linked above?

Yes the above commit fixes this error

**Comment by pmattern** [comment] 2016-09-22 12:58
The other day I saw yet another crash of the kind we're discussing here running 2aa9b11. It took place when meteo-qt was attempting to acquire weather data continuously due to issues with openweathermap.org.
The traces were once more slightly different than before and uploaded in a new Gist https://gist.github.com/pmattern/feeb54d02dd194f3c7f1ab9957dd4c94.

**Closed** 2019-12-21 14:16 UTC
